@LibraryManagementSystem.API_HostAddress = https://localhost:7028



###

GET {{LibraryManagementSystem.API_HostAddress}}/api/book

###

@title = The Great Gatsby
GET {{LibraryManagementSystem.API_HostAddress}}/api/book/search?title={{title}}&author=&genre=Classic

###



###
