@LibraryManagementSystem.API_HostAddress = https://localhost:7028



###

GET {{LibraryManagementSystem.API_HostAddress}}/api/book

###

@author = F. Scott Fitzgerald
GET {{LibraryManagementSystem.API_HostAddress}}/api/book/search?author={{author}}

###



###

POST {{LibraryManagementSystem.API_HostAddress}}/api/book
Content-Type: application/json

 {
  "title": "The Fault in Our Stars",
  "isbn": "978-0142424179",
  "language": "English",
  "edition": "First",
  "totalCopies": 20,
  "availableCopies": 20,
  "shelfLocation": "C1",
  "status": "Available",
  "authorID": 1,
  "genreID": 2
}


###

@id=91
DELETE {{LibraryManagementSystem.API_HostAddress}}/api/book/{{id}}

###

PATCH {{LibraryManagementSystem.API_HostAddress}}/api/book/8
Content-Type: application/json

{
  "title": "The Fault in Our Stars2",
  "isbn": "978-0142424179",
  "language": "English",
  "edition": "First",
  "totalCopies": 20,
  "availableCopies": 21,
  "shelfLocation": "C1",
  "status": "Available",
  "authorID": 1,
  "genreID": 3
}

###
